# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from user.v1 import user_pb2 as user_dot_v1_dot_user__pb2


class UserServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUserById = channel.unary_unary(
                '/user.v1.UserService/GetUserById',
                request_serializer=user_dot_v1_dot_user__pb2.GetUserRequest.SerializeToString,
                response_deserializer=user_dot_v1_dot_user__pb2.GetUserResponse.FromString,
                )
        self.GetAllUsers = channel.unary_unary(
                '/user.v1.UserService/GetAllUsers',
                request_serializer=user_dot_v1_dot_user__pb2.GetAllUsersRequest.SerializeToString,
                response_deserializer=user_dot_v1_dot_user__pb2.GetAllUsersResponse.FromString,
                )


class UserServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetUserById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUserById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserById,
                    request_deserializer=user_dot_v1_dot_user__pb2.GetUserRequest.FromString,
                    response_serializer=user_dot_v1_dot_user__pb2.GetUserResponse.SerializeToString,
            ),
            'GetAllUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllUsers,
                    request_deserializer=user_dot_v1_dot_user__pb2.GetAllUsersRequest.FromString,
                    response_serializer=user_dot_v1_dot_user__pb2.GetAllUsersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'user.v1.UserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UserService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetUserById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/user.v1.UserService/GetUserById',
            user_dot_v1_dot_user__pb2.GetUserRequest.SerializeToString,
            user_dot_v1_dot_user__pb2.GetUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAllUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/user.v1.UserService/GetAllUsers',
            user_dot_v1_dot_user__pb2.GetAllUsersRequest.SerializeToString,
            user_dot_v1_dot_user__pb2.GetAllUsersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
