# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user/v1/user.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from orders.v1 import order_pb2 as orders_dot_v1_dot_order__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12user/v1/user.proto\x12\x07user.v1\x1a\x15orders/v1/order.proto\"j\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\x12 \n\x06orders\x18\x05 \x03(\x0b\x32\x10.orders.v1.Order\"\x1c\n\x0eGetUserRequest\x12\n\n\x02id\x18\x01 \x01(\x05\".\n\x0fGetUserResponse\x12\x1b\n\x04user\x18\x01 \x01(\x0b\x32\r.user.v1.User\"\x14\n\x12GetAllUsersRequest\"3\n\x13GetAllUsersResponse\x12\x1c\n\x05users\x18\x01 \x03(\x0b\x32\r.user.v1.User2\x99\x01\n\x0bUserService\x12@\n\x0bGetUserById\x12\x17.user.v1.GetUserRequest\x1a\x18.user.v1.GetUserResponse\x12H\n\x0bGetAllUsers\x12\x1b.user.v1.GetAllUsersRequest\x1a\x1c.user.v1.GetAllUsersResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user.v1.user_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USER._serialized_start=54
  _USER._serialized_end=160
  _GETUSERREQUEST._serialized_start=162
  _GETUSERREQUEST._serialized_end=190
  _GETUSERRESPONSE._serialized_start=192
  _GETUSERRESPONSE._serialized_end=238
  _GETALLUSERSREQUEST._serialized_start=240
  _GETALLUSERSREQUEST._serialized_end=260
  _GETALLUSERSRESPONSE._serialized_start=262
  _GETALLUSERSRESPONSE._serialized_end=313
  _USERSERVICE._serialized_start=316
  _USERSERVICE._serialized_end=469
# @@protoc_insertion_point(module_scope)
