# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0border.proto\x12\x11org.order.service\x1a\x1fgoogle/protobuf/timestamp.proto\"p\n\x05Order\x12\x10\n\x08order_id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12.\n\norder_date\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x14\n\x0ctotal_amount\x18\x04 \x01(\x05\"(\n\x15OrdersByUserIdRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"B\n\x16OrdersByUserIdResponse\x12(\n\x06orders\x18\x01 \x03(\x0b\x32\x18.org.order.service.Order2x\n\x0cOrderService\x12h\n\x11GetOrdersByUserId\x12(.org.order.service.OrdersByUserIdRequest\x1a).org.order.service.OrdersByUserIdResponseB\x02P\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'P\001'
  _ORDER._serialized_start=67
  _ORDER._serialized_end=179
  _ORDERSBYUSERIDREQUEST._serialized_start=181
  _ORDERSBYUSERIDREQUEST._serialized_end=221
  _ORDERSBYUSERIDRESPONSE._serialized_start=223
  _ORDERSBYUSERIDRESPONSE._serialized_end=289
  _ORDERSERVICE._serialized_start=291
  _ORDERSERVICE._serialized_end=411
# @@protoc_insertion_point(module_scope)
