version: '3.7'

services:
  orders-db:
    image: postgres:10.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5431:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql